name: Prevents you from committing passwords and other sensitive information to a git repository.

on:
  pull_request:
    branches: [ $default-branch ]
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update
          apt install curl zip unzip make -y
          curl -LJO https://github.com/awslabs/git-secrets/archive/master.zip
          unzip git-secrets-master.zip
      - name: Scan repo
        run: |
          git-secrets --install
          git-secrets --scan-history
        